---
- name: Backup Mikrotik
  hosts: mikrotik
  gather_facts: false
  vars:
    backup_dir: "/root/network/backup"

  tasks:
    - name: Export MikroTik configuration to file (secure)
      ansible.netcommon.command:
        command: /export file={{ inventory_hostname }}_backup
      delegate_to: localhost
      become: true
      register: export

    - name: Download the backup file from the MikroTik device (if export successful)
      ansible.builtin.fetch:
        src: "/{{ inventory_hostname }}_backup.rsc"  # Assuming .rsc extension
        dest: "{{ backup_dir }}/"
        flat: yes
      when: export is defined  # Download only if export succeeded
