---
- name: Backup Mikrotik
  hosts: mikrotik
  gather_facts: false
  vars:
    backup_dir: "/root/network/backup"
  tasks:
  - name: Export MikroTik Configuration
    community.routeros.command:
      commands: /export
    register: export_data
    delegate_to: localhost
  - name: Create Backup File with Timestamp
    ansible.builtin.template:
      src: mikrotik_config.j2
      dest: "{{ backup_dir }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
    vars:
      config: "{{ export_data.stdout }}"
    delegate_to: localhost
