---
- name: Backup Mikrotik Routers
  hosts: mikrotik
  gather_facts: no

  tasks:
    - name: Export configuration on Mikrotik router
      community.routeros.routeros_command:
        commands:
          - /export file=backup_{{ inventory_hostname }}
      register: backup_output

    - name: Download backup file
      community.routeros.routeros_file:
        src: backup_{{ inventory_hostname }}.rsc
        dest: /root/network/backup/backup_{{ inventory_hostname }}.rsc
        mode: get

    - name: Remove backup file from Mikrotik router
      community.routeros.routeros_command:
        commands:
          - /file remove backup_{{ inventory_hostname }}
      when: backup_output is succeeded
