---
- name: Backup Mikrotik Routers
  hosts: mikrotik
  gather_facts: no

  tasks:
    - name: Export configuration on Mikrotik router
      ansible.builtin.shell: "/export file=backup_{{ inventory_hostname }}"
      register: backup_output

    - name: Download backup file
      ansible.builtin.fetch:
        src: /backup_{{ inventory_hostname }}.rsc
        dest: /root/network/backup
        flat: yes

    - name: Remove backup file from Mikrotik router
      ansible.builtin.shell: "/file remove backup_{{ inventory_hostname }}"
      when: backup_output is succeeded

