---
- name: Backup Mikrotik
  hosts: mikrotik
  gather_facts: false
  vars:
    backup_dir: "/root/network/backup"
  tasks:
    - name: Export Mikrotik configuration to file
      ansible.builtin.shell: >-
        sshpass -p '{{ ansible_password }}' ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ inventory_hostname }} '/export file={{ inventory_hostname }}_backup'
      delegate_to: localhost
      register: export

    - name: Download the backup file
      ansible.builtin.fetch:
        src: "/{{ inventory_hostname }}_backup.rsc"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.rsc"
        flat: yes
      delegate_to: localhost
      when: export is defined
